# Generated by Django 4.2.16 on 2024-11-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sucursal',
            field=models.CharField(choices=[('PlazaOeste', 'Plaza Oeste'), ('MallAraucoMaipu', 'Mall Arauco Maipu'), ('CinepolisMaipu', 'Cinepolis Maipu'), ('PlazaOeste', 'Plaza Oeste'), ('PlazaVespucio', 'Plaza Vespucio')], max_length=100),
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloPeliculas.pelicula')),
            ],
        ),
    ]
