# Generated by Django 4.2.16 on 2024-11-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloPeliculas', '0002_alter_pelicula_sucursal_reseña'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
